### ISSUE TITLE
Per-Call Heap Allocations

### ISSUE THREAD

**Issue by stonstad** [ChromaControl/SDK#1]
Through Unity profiling I discovered that SetLedsColorsBufferByDeviceIndex(int deviceIndex, CorsairLedColor[] ledsColors) allocates per method invocation. For high frequency color change scenarios, this can be a little problematic (i.e. Unity3d).  

I should probably create a PR for this, but here is a non-allocating version if buffer sizes remain fixed. It requires unsafe.

``` csharp
private static IntPtr _LedsPtr = IntPtr.Zero;
private static int _AllocatedSize = 0;

public static bool SetLedsColorsBufferByDeviceIndex(int deviceIndex, CorsairLedColor[] ledsColors)
{
    int size = ledsColors.Length;
    int corsairLedColorSize = Marshal.SizeOf<CorsairLedColor>();

    // Only allocate new memory if the size has increased
    if (size > _AllocatedSize)
    {
        // Free previous memory if it exists
        if (_LedsPtr != IntPtr.Zero)
        {
            Marshal.FreeHGlobal(_LedsPtr);
        }

        _LedsPtr = Marshal.AllocHGlobal(corsairLedColorSize * size);
        _AllocatedSize = size;
    }

    // safe approach which allocates due to boxing inside of Marshal.StructureToPtr.
    //for (int i = 0; i < size; i++)
    //{
    //    Marshal.StructureToPtr(ledsColors[i], _LedsPtr + corsairLedColorSize * i, true);
    //}

    // unsafe approach which does not allocate
    unsafe
    {
        CorsairLedColor* pLeds = (CorsairLedColor*)_LedsPtr.ToPointer();
        for (int i = 0; i < size; i++)
        {
            pLeds[i] = ledsColors[i];
        }
    }

    bool result = SetLedsColorsBufferByDeviceIndexNative(deviceIndex, size, _LedsPtr);

    // Do not free the memory here as we're reusing it
    // Marshal.FreeHGlobal(ledsPtr);

    return result;
}
 
```

**Comment by andrewbabbittdev** [comment]
Please submit a PR for this change, we like to retain code authorship where possible :)

**Comment by andrewbabbittdev** [comment]
Going forward, I will not be maintaining a Corsair library. All the libs under this org have historically been just for use with Chroma Control, but we are shifting focus over to OpenRGB as both Armory Crate and ICue have just become a support and maintenance nightmare as time has gone on.

The existing source for the ICUE lib can be found on commit 7f78cbfdb27f75214463688f2570b21825f3c9d1

There are other Corsair libs available such as RGB.NET, but I leave the source available for anyone to take (it is under MIT anyways). Also willing to transfer NuGet package ownership if someone wants to take up maintaining it themselves.
