### ISSUE TITLE
iCUE SDK v4.x Support

### ISSUE THREAD

**Issue by stonstad** [ChromaControl/SDK#2]
Hi there!  This is a great API.  Any thoughts to supporting iCUE SDK v4?  https://github.com/CorsairOfficial/cue-sdk/releases

**Comment by andrewbabbittdev** [comment]
This is definitely something I want to do soon, ideally for our upcoming ChromaControl release. Seeing as this is a major release and reworks a lot of stuff, I cant give exact time estimates on the new SDK until I dive in and start comparing changes from v3.

**Comment by andrewbabbittdev** [comment]
Quick peek doesnt seem too bad, so yeah this will be done for the next ChromaControl release.

I don't have estimates on availability as of right now, hoping to get some time to work on this soon. Everything in this org is entirely worked on as a part of my limited free time right now.

**Comment by stonstad** [comment]
Cool, I want to sponsor you.  Doing so now.

**Comment by stonstad** [comment]
Hey Andrew. Just circling back to see if future development for CUESDK.NET is planned.  iCUE SDK v4.x support is likely required for this project to remain viable.

**Comment by andrewbabbittdev** [comment]
Yes, this has just been low on my priority list. Also open to PRs if it's needed sooner. We have a focus on OpenRGB right now that's been a higher priority.

Is there a deadline to migrate to v4?

**Comment by stonstad** [comment]
Hey Andrew!  Much appreciate the response.  I'm getting closer to sharing a game on Steam and I have to decide whether to remove Corsair lighting support since 3.x is not commonly used.  OpenRGB user .NET 6/7/8, which Unity does not currently support.  Your Corsair implementation is very good and I'd like to continue using it, if possible.  I'm happy to compensate you for your time if you are interested.

**Comment by andrewbabbittdev** [comment]
We multitarget with support for .NET Standard 2.1 and .NET 4.5.

If you need us to compile for additional versions of .NET we just need to know which versions need to be supported to work with Unity. This is much simpler than upgrading to a new version of the ICue API.

**Comment by andrewbabbittdev** [comment]
A full list of supported .NET versions can be found on the Nuget page here: https://www.nuget.org/packages/CUESDK.NET#supportedframeworks-body-tab

**Comment by andrewbabbittdev** [comment]
Starting work on updates to this project to bring it up to latest protocol version

**Comment by andrewbabbittdev** [comment]
Going forward, I will not be maintaining a Corsair library. All the libs under this org have historically been just for use with Chroma Control, but we are shifting focus over to OpenRGB as both Armory Crate and ICue have just become a support and maintenance nightmare as time has gone on.

The existing source for the ICUE lib can be found on commit 7f78cbfdb27f75214463688f2570b21825f3c9d1

There are other Corsair libs available such as RGB.NET, but I leave the source available for anyone to take (it is under MIT anyways). Also willing to transfer NuGet package ownership if someone wants to take up maintaining it themselves.

**Comment by stonstad** [comment]
HI Andrew --

Apologies that I am just now seeing your responses. I am sorry to hear that you won't be maintaining the Corsair library. I'll take a look at OpenRGB. 

If something changes and you decide to circle back to v4 protocol support -- and would like to do this via a paid contract, please feel free to contact me at shaun (at-sign) stellarstudio.com. 

Thank you for contributions. It has been a joy to work with your librayr.
